version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=books

  frontend:
    build: ./frontend
    ports:
      - "8082:8080"  # Changed host port to 8081 to avoid conflict
    volumes:
      - ./frontend:/app

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
